version: "3"

services:
  
  web-mvc:
    image: bryanlimadev/nerdstoreenterprise-web-mvc-ecommerce:latest
    container_name: nerdstoreenterprise-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001