version: "3"

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-nerdstoreenterprise
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstoreenterprise"
      RABBITMQ_DEFAULT_PASS: "nerdstoreenterprise"

  sql-server:
    image: bryanlimadev/nerdstoreenterprise-sql-server:latest
    container_name: nerdstoreenterprise-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"

  web-mvc:
    image: bryanlimadev/nerdstoreenterprise-web-mvc-ecommerce:latest
    container_name: nerdstoreenterprise-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - api-catalogo
      - api-identidade
      - api-cliente
      - api-bff-compras

  api-identidade:
    image: bryanlimadev/nerdstoreenterprise-api-identidade:latest
    container_name: nerdstoreenterprise-api-identidade    
    build: 
      context: ../src
      dockerfile: ./services/NSE.Identidade.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5101
    depends_on:
      - rabbitmq
      - sql-server
          
  api-carrinho:
    image: bryanlimadev/nerdstoreenterprise-api-carrinho:latest
    container_name: nerdstoreenterprise-api-carrinho
    build: 
      context: ../src
      dockerfile: ./services/NSE.Carrinho.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5201
    depends_on:
      - rabbitmq
      - api-identidade
      - sql-server

  api-catalogo:
    image: bryanlimadev/nerdstoreenterprise-api-catalogo:latest
    container_name: nerdstoreenterprise-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5301
    depends_on:
      - rabbitmq
      - sql-server

  api-cliente:
    image: bryanlimadev/nerdstoreenterprise-api-cliente:latest
    container_name: nerdstoreenterprise-api-cliente    
    build: 
      context: ../src
      dockerfile: ./services/NSE.Clientes.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5401
    depends_on:
      - rabbitmq
      - api-identidade
      - sql-server  

  api-bff-compras:
    image: bryanlimadev/nerdstoreenterprise-api-bff-compras:latest
    container_name: nerdstoreenterprise-api-bff-compras
    build: 
      context: ../src
      dockerfile: ./api gateways/NSE.Bff.Compras/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5501
    depends_on:
      - rabbitmq
      - api-identidade
      - api-carrinho
      - api-pagamento
      - api-pedido
          
  api-pagamento:
    image: bryanlimadev/nerdstoreenterprise-api-pagamento:latest
    container_name: nerdstoreenterprise-api-pagamento    
    build: 
      context: ../src
      dockerfile: ./services/NSE.Pagamentos.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5601
    depends_on:
      - rabbitmq
      - api-identidade
      - api-pedido
      - sql-server
          
  api-pedido:
    image: bryanlimadev/nerdstoreenterprise-api-pedido:latest
    container_name: nerdstoreenterprise-api-pedido    
    build: 
      context: ../src
      dockerfile: ./services/NSE.Pedidos.API/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5701
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade

  nerdstoreenterprise-server:
    image: bryanlimadev/nerdstoreenterprise-server:latest
    container_name: nerdstoreenterprise-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-mvc